# Generated by Django 5.2.5 on 2025-08-30 14:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRICAO', models.TextField(max_length=100)),
                ('REGISTRADO', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks_Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANEXO', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks_Prioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRICAO', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRICAO', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRICAO', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMENTARIO', models.TextField(max_length=1000)),
                ('REGISTRADO', models.DateTimeField(default=django.utils.timezone.now)),
                ('TASK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TASK', to='Tarefas.tasks')),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='PRIORIDADE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PRIORIDADE', to='Tarefas.tasks_prioridade'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='STATUS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='STATUS', to='Tarefas.tasks_status'),
        ),
    ]
