# Generated by Django 5.2.5 on 2025-08-30 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks_attachments',
            name='TASK',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='Tarefas.tasks'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks_comments',
            name='TASK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Tarefas.tasks'),
        ),
    ]
