# Generated by Django 5.2.5 on 2025-08-30 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarefas', '0002_tasks_attachments_task_alter_tasks_comments_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks_attachments',
            name='TIPO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos', to='Tarefas.tipo_attachments'),
        ),
        migrations.AlterField(
            model_name='tasks_attachments',
            name='ANEXO',
            field=models.FileField(upload_to='anexos/'),
        ),
    ]
